# Generated by Django 6.0.2 on 2026-05-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreedor', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='panel_deuda.deuda')),
            ],
        ),
    ]
