# Generated by Django 6.0.2 on 2026-05-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracion_meses', models.IntegerField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_meta', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='metas/')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(default='Efectivo', max_length=50)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='panel_ahorros.meta')),
            ],
        ),
    ]
